spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mc_config?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    #连接池的配置信息
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 3600000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 192.168.0.132
    port: 6379
    password: root
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMinIdle: 0
    poolMaxWait: 500
    poolMaxActive: 200
    database: 0
    timeout: 0




