server:
  port: 8003
spring:
  application:
    name: eureka-admin-client
eureka:
  instance:
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8001}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always