server:
  port: 8080
  servlet:
    context-path: /dubbo

# Dubbo
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
    logger: slf4j
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
  consumer:
      check: false
  scan:
    base-packages: com.example.demo.dubbo.controller
#debug: true
