server:
  port: 8081

#邮箱服务器地址(此处使用的是163的邮箱)
spring:
  mail:
    host: smtp.163.com
    username: typ005@163.com   #用户名
    password: 123456   #授权码
    default-encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: admin
    initial-size: 1
    min-idle: 1
    max-active: 20
