server:
  port: 8081

# Mybatis
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true #±Ì√˚Õ’∑Â”≥…‰

# mysql
spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

#¥Ú”°sql
logging:
  level:
    com.example.demo.webflux.mapper : debug